version: '3'
services:
  mySqlDatabase:
    image: 'mysql:5.7'
    container_name: mySqlDatabase
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=product
    ports:
      - '3307:3306'